---
#------- 检测 ngine 是否存在
- name: check {{nginx_version}} nginx_bin
  command: ls /usr/local/{{nginx_version}}/sbin/nginx
  register: bin
  ignore_errors: True

- include: nginx-pkg.yml
  when: bin|failed

- name: unzip {{nginx_version}} files
  unarchive: src="{{nginx_version}}.tar.gz" dest=/opt/
  when: bin|failed

- name: compile {{nginx_version}}
  script: compile-nginx.sh "{{nginx_version}} {{args}}"
  when: bin|failed

#------- 检测配置是否存在
#- name: check {{nginx_version}} php-fpm.conf
#  command: ls /usr/local/{{nginx_version}}/etc/php-fpm.conf
#  register: fpm
#  ignore_errors: True
#
#- name: php-fpm.conf
#  template: src=php-fpm.conf dest=/usr/local/{{nginx_version}}/etc/
#  when: fpm|failed
#
#-------6 7 启动脚本
- name: CentOS 7 systemd script 
  template: src=nginx-7.service dest=/lib/systemd/system/{{nginx_version}}.service
  when: ansible_distribution_major_version == '7'

- name: CentOS 6 upstart script 
  template: src=nginx-6.service dest=/etc/init.d/{{nginx_version}} mode=0755
  when: ansible_distribution_major_version == '6'

#-------启动服务
- name: start nginx service
  service: name={{nginx_version}} state=restarted enabled=yes

#-------删除编译目录
- name: check compile {{nginx_version}} dir
  command: ls /opt/{{nginx_version}}
  register: dir
  ignore_errors: True

- name: del {{nginx_version}} compile dir
  file: dest=/opt/{{nginx_version}} state=absent
  when: dir|success
