- block:
  - name: rpm package copy
    copy: src={{zabbix_agent_package}} dest=/opt/{{zabbix_agent_package}}
  - name: yum install  
    yum: name=/opt/{{zabbix_agent_package}} state=installed
  - name: conf file
    template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
    notify:
      - restart zabbix-agent
  #- name: python module
  #  pip: name=psutil state=latest
  when: ansible_os_family == "RedHat" and ansible_userspace_architecture == "x86_64"
